site_name: ThemaKit
site_description: Modern UI Components for React.
site_author: ThemaKit
site_url: https://thema.js.org/docs

theme:
  name: material
  palette:
    primary: teal
    accent: teal
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.footer

  logo: assets/logo.svg
  favicon: assets/icon.png
  search:
    provider: lunr
    lang: en
    index: true
    search_index: true
    search_suggest: true
    search_highlight: true

repo_url: https://github.com/themakit/docs
edit_uri: edit/main/docs/

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.highlight
  - tables
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Components:
    - Layout:
      - Container: components/layout/container.md
      - Grid: components/layout/grid.md
      - Flex: components/layout/flex.md
      - Stack: components/layout/stack.md
    - Inputs:
      - Button: components/inputs/button.md
      - TextField: components/inputs/textfield.md
      - Select: components/inputs/select.md
      - Checkbox: components/inputs/checkbox.md
    - Display:
      - Card: components/display/card.md
      - Modal: components/display/modal.md
      - Alert: components/display/alert.md
      - Toast: components/display/toast.md
  - Theming:
    - Overview: theming/overview.md
    - Custom Themes: theming/custom-themes.md
    - Dark Mode: theming/dark-mode.md
  - Animations:
    - Overview: animations/overview.md
    - Transitions: animations/transitions.md
    - Keyframes: animations/keyframes.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/themakit
      name: View on GitHub
copyright: Copyright &copy; 2025 ThemaKit. All rights reserved.
